name: Scala

on:
  pull_request: {}
  push:
    branches:
      - second-edition

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - graalvm11-ce
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ‚ô®Ô∏è"
        uses: coursier/cache-action@v4.1

      - name: "Starting up Postgres & Redis üê≥"
        run: docker-compose up -d

      - name: "Install Nix ‚ùÑÔ∏è"
        uses: cachix/install-nix-action@v13

      - name: "Install Cachix ‚ùÑÔ∏è"
        uses: cachix/cachix-action@v10
        with:
          name: practical-fp-in-scala
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Run with ${{ matrix.java }} üöÄ"
        run: nix-shell --argstr jdk "${{ matrix.java }}" --run "sbt 'scalafmtCheckAll;test;it:test'"

      - name: "Shutting down Postgres & Redis üê≥"
        run: docker-compose down
